version: '3'

services:

  app:
    container_name: ecommerce_frontend
    build:
      context: ./ops/node
    volumes:
      - .:/app
    networks:
      - vue

  nginx:
    container_name: nginx-frontend
    build:
      context: ./ops/node

    volumes:
      - ./:/app
      - ./ops/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - vue
networks:
  vue: